### ISSUE TITLE
Pool plotting

### ISSUE THREAD

**Issue by yugo45** [abueide/harry-plotter#115]
Hi. Great plotter and works fine. Very efficient.
Will there be an upadte for plotting pool-plots? Would be great.

Greetings Benjamin

**Comment by rattfieldnz** [comment]
It would be great to implement MadMax plotter executable instead of the painfully-slow chia.exe. This is a reason why I've (unfortunately) had to stop using HarryPlotter, and now use PSChiaPlotter (which has MadMax integration). If HarryPlotter does integrate MadMax, I'll switch back. I'd fork this repo and do it myself, although it's been a few years since working with desktop apps. Oddly enough, my one and only machine is preoccupied with Chia plotting, so I'd have to stop this to do anything else.

**Comment by yugo45** [comment]
would even be nicer

**Comment by abueide** [comment]
done in 1.2.0, mad max support coming in a later release
