### ISSUE TITLE
Harry Plotter” is damaged and can’t be opened.

### ISSUE THREAD

**Issue by domizi** [abueide/harry-plotter#19]
“Harry Plotter” is damaged and can’t be opened. You should move it to the Bin."

Doesn't work on the newest macOS Catalina 10.15.7.
Tried redownloading via cable, wifi multiple times.

**Comment by abueide** [comment]
it happens on my mac as well, something is probably wrong with the auto build system. I'll try to fix it today

**Comment by abueide** [comment]
@crbelaus @domizi try redownloading the 1.1.3 mac build and let me know if it works (I replaced the build with a fixed version, should hopefully work now)

**Comment by abueide** [comment]
ah nevermind interesting. so it works on my local machine with a fresh build, but if i upload it to github and download it again and run it I end up getting the error again.

**Comment by domizi** [comment]
Unfortunately still doesn't work. I also tried to test on the older macos (10.14.6) without any luck.

**Comment by abueide** [comment]
@domizi so I've figured out what the problem was. In short I need to pay $99/year to join the developer program & sign the app. Any donations to this address or any paypal tips with the message "macos support" or something similar will go towards doing exactly that.

paypal: andrew@abueide.com
chia macos address: xch1zuxzds2y709amgaz7xmuqmj45l0r3pgjc36kcg090nuer2hdd9aqh2p8z4

Otherwise the workaround is to install the .pkg file instead and follow the instructions found here
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by abueide** [comment]
if you have any issues with using the workaround, let me know and I'll reopen it.
