### ISSUE TITLE
No Stats

### ISSUE THREAD

**Issue by Grochonou** [abueide/harry-plotter#20]
Hi, i can see there is nothing in the stats or next to the steps theres are nothing in the "Last Plot Time" etc, it could be cool to have informations about it

**Comment by abueide** [comment]
Yeah so currently theres a bug where its not reading the time the plot took correctly so its staying at 0 plots created and 0 time average/estimated etc. This will be fixed in the next release hopefully. As for the stats tab there is planned to be all time stats for all plots you've ever made with harry plotter, but that isn't implemented yet.

**Comment by abueide** [comment]
Fixed in 1.1.4
