### ISSUE TITLE
only using 1 numa node?

### ISSUE THREAD

**Issue by bandit8623** [abueide/harry-plotter#25]
![node0](https://user-images.githubusercontent.com/9302078/119241524-aa906400-bb1c-11eb-89ea-85b474d989d3.PNG)
hi great program!

i have a 2 socket server with 2 cpus.  i have 16 plots going and it seems to be only using node 0.  node 1 isnt really being touched.
is this intended?

thx

x9drh-7tf
2x e5-2697v2's
128 gig ram
![potter](https://user-images.githubusercontent.com/9302078/119241548-dd3a5c80-bb1c-11eb-815d-7356392d7c29.PNG)

**Comment by abueide** [comment]
Huh interesting. I don't actually have a server with 2 cpus so its difficult for me to test. Harry Plotter just spawns the chia.exe executable with java's ProcessBuilder api, I'll look a bit deeper into how it works to see if it specifies anything on which cpu it can use.

**Comment by bandit8623** [comment]
I'm not home at the moment , but using the built-in plotter it would spread out more across the nodes. I'll be home tomorrow to take a look after more plots are going. Thx for what you do

**Comment by bandit8623** [comment]
so it seems to have evened out after the 1st round of plots completed.  i will say for some reason i am getting less plots per day.  
i was getting 32 a day with the old gui.  its saying ill have 24 a day with harry plotter.  

same 16 plots going at the same time.  im still trying to figure out the best way to stagger on this app.  do i have to make more than 16 plots to get the app to run more than 16?  or can each plot i set up run more than one at a time?
![cpu](https://user-images.githubusercontent.com/9302078/119271837-eda81100-bbc8-11eb-880f-bc3dcb814a28.PNG)

also not getting any percentage change on the left.  plots are completing though so i know its working. this is my screen after running fore a day.
![24hoursno percent](https://user-images.githubusercontent.com/9302078/119271895-319b1600-bbc9-11eb-9062-61617fd7096b.PNG)

**Comment by bandit8623** [comment]
i just added a few more plots to get my cpu at 90%.  its definitely favoring to fill up node 0 first and then use the 2nd.  just different than how the chia gui did it.  

hey im just happy your app doesnt crash and i can see whats going on :) thx again

**Comment by abueide** [comment]
@bandit8623 
yes you're right it does prioritize the jobs higher in the list when starting a new one, since I thought this would be preferable for users to decide which jobs get prioritized first. (E.g. you could put a plot for each drive at the top, then it'd balance making plots across each drive before starting to run parallel plots on the same drives hopefully increasing in faster speeds). I do need to add a way to make it easier to move the jobs around to change up the priority without duplicating/deleting jobs.

I could also add a different balancing mode, just let me know how you'd prefer it to work.

"same 16 plots going at the same time. im still trying to figure out the best way to stagger on this app. do i have to make more than 16 plots to get the app to run more than 16? or can each plot i set up run more than one at a time?"

yes you do have to make more than 16 plot jobs to make it run more than 16. the stagger settings act as a limiter on how many plot jobs can be running in each phase at once. leave the phase 1 & phase 2-4 stagger at 0 if you want no maximum. But if you set phase 1 to 8 for example it won't start any new plot jobs until there are less than 8 plot jobs currently in phase 1 at which point it'll automatically fire up the next highest priority plot job.

Let me know if you have any questions or suggestions, also if you still see performance decreases after this.

**Comment by bandit8623** [comment]
thanks so much!  

I added more and i think i have the stagger down now. ill run for a few days to see how it goes!  thx for your prompt responses!
i probably have a pretty unique setup.  as im running 16 raid 0 arrays off a megasas raid controller.  i got it all free so i decided to go this route vs ssd drives.  

i was getting 32 plots a day with the built in gui.   now that i have the stagger setup with your app ill update tomorrow.

**Comment by bandit8623** [comment]
![IMG_20210523_164041](https://user-images.githubusercontent.com/9302078/119277540-fc50f100-bbe5-11eb-984d-56d3b6ef259e.jpg)
![IMG_20210523_164108](https://user-images.githubusercontent.com/9302078/119277541-fd821e00-bbe5-11eb-9ccd-9967d98fa853.jpg)
figured i would share my setup.  messy cable management i know! but slowly cleaning it up LOL

**Comment by abueide** [comment]
wow nice thats sick. I hope I can have a setup like that one day xD

**Comment by bandit8623** [comment]
update!
from 6pm yesterday to 6pm today 55 plots completed.  amazing work
