### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by gtaccountz** [abueide/harry-plotter#26]
I have 2 machines that are plotting. One runs Harry Plotter just fine, installed and ran no problem. The second machine has an error of "Failed to Launch JVM" upon start up.

I'm likely missing a prerequisite install.  I checked for things like java, c++, etc. and have them all installed. Any suggestions?

Also, it may be helpful to list out prerequisite software required to run Harry Plotter. Likely an easy fix to my local machine (the missing software) and the github page (prerequisite software)

**Comment by abueide** [comment]
I don't think there are any prerequisite software. I think for the most part the installer handles it on its own & packages a jvm & all the dependencies with it. If you'd like shoot me an email and we can discord or something. I'd be happy to help you debug it.

Otherwise I can send you a build with the console enabled then you can let me know what the error you're getting is.

**Comment by jess4140** [comment]
i had this problem also,to fixe it i install chia software..

**Comment by gtaccountz** [comment]
> i had this problem also,to fixe it i install chia software.. and the jdk16

This did not work for me.

> I don't think there are any prerequisite software. I think for the most part the installer handles it on its own & packages a jvm & all the dependencies with it. If you'd like shoot me an email and we can discord or something. I'd be happy to help you debug it.
> 
> Otherwise I can send you a build with the console enabled then you can let me know what the error you're getting is.
> 
> You can also try compiling from source, its really a really simple 1 command thing which you can find on the readme after installing jdk 16

Tried compiling from source, same error.  Downloaded WIX toolset as well so that I could compile.  I'll send you a DM.

**Comment by gtaccountz** [comment]
Ah I figured it out!  Having ANY old version of chia in the (USER)/Appdata/local/chia-blockchain folder caused the error.  I had app-1.1.5 and app-1.1.6 folders inside there.  Deleting 1.1.5 allowed the software to boot right up.

**Comment by jess4140** [comment]
I had the problem cause my machine did`t have anything on it like chia and jdk , that is why i had the bug,well you learn something and so do i..

**Comment by abueide** [comment]
Interesting, thanks for testing it out guys. I'll do some more testing on my own with the info you guys provided and see if I can provide a fix.

**Comment by abueide** [comment]
let me know if this still happens in 1.1.5

**Comment by jmz-bit** [comment]
I have this "Failed to launch JVM" problem. Today I downloaded 1.1.6 and first app start was OK. Second time was also OK. When I started it 3rd time and set some plots to do I decided to stop them and restart the app. Since then I have Failed to launch JVM error. Tried to install java and jdk16. Still this same problem. I did check do I have any older version of Chia ((USER)/Appdata/local/chia-blockchain) and I don't have it. I tried to rename chia folder and this time I didn't get the error but app was asking where my chia folder is. I provided path to renamed folder but then this same error appeared. This program looks like something that I was looking for... but sadly is not working on my computer. Any ideas and help?

**Comment by jmz-bit** [comment]
I managed to fix it. Removed Harry-Plotter app and removed .harryplotter folder manually. Then installed it again and it is working now. 

PS. I discovered accidentally something else. If you will run this app as administrator you will not see network drives (mapped drives visible under My Computer) when trying to add path to final destination for plots.

**Comment by trs-80** [comment]
I ran into the same issue, for it me it had something to with a bad jobs.json file under .harryplotter it started right up. I will need to recreate my jobs, but luckily I didn't have very many setup yet.

**Comment by abueide** [comment]
@trs-80 in newer versions this gets handled automatically and backs up your old jobs.json and makes a new one. if you haven't already try out the 1.1.8 release it seems to be pretty stable now

**Comment by trs-80** [comment]
@abueide I am running v1.1.8 and encountered this problem

**Comment by abueide** [comment]
interesting. so when you deleted your jobs.json file it worked on 1.1.8?

**Comment by abueide** [comment]
I think this should be fixed now. It had to do with failures when reading log files

**Comment by Crimsonking314** [comment]
I am using version 1.1.11 and am having the same issue. I have uninstalled and reinstalled without luck, updated Java and deleted old versions of chia still nothing.

**Comment by abueide** [comment]
@Crimsonking314 did you upgrade recently to 1.1.11? deleting/backing up ~/.harryplotter/jobs.json should fix the issue for now. I'm working on a fix for 1.1.12

**Comment by Crimsonking314** [comment]
@abueide it was the first time installing but I found the issue. It could not find my chia.exe file because I had to do a system restore on my pc and it got removed but left behind all the other files so I didn't notice until trying to plot. Thanks for the quick response.
