### ISSUE TITLE
Plotter log files

### ISSUE THREAD

**Issue by dandyrand** [abueide/harry-plotter#28]
When starting jobs through harry plotter, the default log folder is not being populated. Does harry plotter save the log file elsewhere?

**Comment by abueide** [comment]
currently harry plotter does not save the log files, it does save some stats parsed from them in ~/.harryplotter though.

Soon I'll also start logging the files to ~/.harryplotter so that way harry plotter can reattach and you'll be able to restart harry plotter & update while plots are still running. When I do this I'll also add an option to keep old logs.

**Comment by konkersgg** [comment]
> so is there any way to access the individual logs for each plot running so that i can parse it with external tool?

apparently not yet qq

**Comment by abueide** [comment]
not yet but coming soon

**Comment by SauravKumal** [comment]
awsome. wold be good if running plot logs are also deleted while clearing temp directory
