### ISSUE TITLE
GUI freezes

### ISSUE THREAD

**Issue by wangxing7714436** [abueide/harry-plotter#61]
Hi, 

I encounter a GUI freezing issue. Yesterday I started 18 tasks and today there are 5 into the next plotting, I checked the task manager and seems the chia.exe is still working but harry plotter's interface is freezing. No button can be clicked.

My gear is 5950x+64G RAM with 5 ssds, 2NVME and 3 sata. CPU occupation is below 100% and other application such as official wallet is alright.

**Comment by abueide** [comment]
ah shoot. have you tried 1.1.6? or is it on both? how many do you have running at any given time?

**Comment by wangxing7714436** [comment]
Not sure if it is a new bug in 1.1.7, I'm a new harry plotter user. I just download the latest version which is 1.1.7, haven't tried previous version. Currently I'm running 18 tasks.

**Comment by abueide** [comment]
would you mind giving 1.1.6 a try and let me know if you have the same issue?

**Comment by wangxing7714436** [comment]
Well, I have some more temp disk arriving today, maybe I can give it a try since I have to stop plotting and install the new disks.

**Comment by firipusan** [comment]
Hi

I have found it freezes after it has completed 3/4 plots per job, regardless of whether it has 1 job or 30 jobs.  The first signs of it about to freeze, is the log starts to become laggy then unusable because it auto scrolls to the bottom before you have had a chance to look at the middle of the log.
