### ISSUE TITLE
Cannot use more than 3.4gb of ram

### ISSUE THREAD

**Issue by firipusan** [abueide/harry-plotter#76]
Hi

I set ram to 6750gib but when I have my plots in parallel I cant seem to get more than about 3.4gb or ram use per plot.

re
phil

**Comment by abueide** [comment]
Hi Phil!

Would you mind sharing a screenshot of your job settings & the beginning of your logs for that job after clicking start?

Something like this:

![image](https://user-images.githubusercontent.com/19354425/120252361-ec6e8800-c249-11eb-8628-24abc4d39893.png)

As you can see I have ram set for this job at 5000, and at the start of the logs it says "Buffer size is: 5000MiB"

If the logs say something different then what you have the job set to then there may be a bug in harry plotter,

**Comment by firipusan** [comment]
Hi

I have 40 plots in parallel with 6 threads each and 6750gib ram. 16 are in phase 1, the rest in phases 2-4. When i look at task monitor it is using only 140gb. When previously it was using much more.

**Comment by abueide** [comment]
Do the logs match the number you put in?

Because the number you put in is the maximum ram that it can use, not necessarily the amount of ram it will use at any given point. I think newer releases of chia see this article from chia.net for more details

![image](https://user-images.githubusercontent.com/19354425/120255014-acf76a00-c250-11eb-80c6-25150c9bbea9.png)

https://www.chia.net/2021/02/22/plotting-basics.html

**Comment by firipusan** [comment]
I think for single plotting the ram does not make difference but when plotting in parallel with a decent number of plots then increase RAM makes a difference.

**Comment by abueide** [comment]
if the correct number is being passed to chia.exe, there's nothing else I can do. you can check that it passing the correct number by using the instructions in my first comment.

let me know if its not passing in the correct ram number and I'll try to fix it, otherwise there's nothing I can fix.

**Comment by josemanuelhda** [comment]
> 
> 
> if the correct number is being passed to chia.exe, there's nothing else I can do. you can check that it passing the correct number by using the instructions in my first comment.
> 
> let me know if its not passing in the correct ram number and I'll try to fix it, otherwise there's nothing I can fix.

I opened another bug with similar problem, in my case is asigning less than 3g ram, it goes to the standard quantity, so I guess something is wrong when your program sends this parameter, I am sorry that I cannot give you the screenshot you ask for because trying to solve it I have deleted and recreated the tasks, but it does not work, if I ask for 3200 it goes fine, but small amounts do not pass whatever filter you may have put in the code

**Comment by abueide** [comment]
let me know if this is still an issue in 1.1.12
